### ISSUE TITLE
Question, does the plugin work with paper

### ISSUE THREAD

**Issue by AshOnDiscord** [NateKomodo/DreamManHunt#8]
Not sure if plugin works with paper or needs other api or only works with vanilla
Aslo this works in1. 15.2 right?

**Comment by codydg** [comment]
I haven't heard of PaperMC until now but according to [PaperMC's website](https://papermc.io/):
"Paper retains compatibility with plugins written for Spigot and Bukkit"

I've used this plugin with Spigot so I'd imagine it'll work with PaperMC, too.

**Comment by NateKomodo** [comment]
It should work with any version of Minecraft that has at minimum the bukkit 1.15 API (Paper has the bukkit API for plugins which is why it's compatible). It should work on 1.16 as well as nothing in the codebase should be version specific, although this is untested.

I'm leaving this open for now, please close it when you resolve your issue

**Comment by NateKomodo** [comment]
Clsoing as no response from OP.
